// Data-driven regression coverage over the live product catalog.
//
// These tests are generated by parametrizing a small set of REAL storefront
// flows across every product in the catalog (and a few value dimensions). Each
// iteration is an independent, uniquely-named test case. They share flows by
// design — this is data-driven coverage, not hand-written unique scenarios.
//
// All flows reach products by clicking through the app (home -> Shop Now ->
// listing -> product), because the SPA does not render on direct deep-link nav.
import { test, expect } from './fixtures.js';
import type AllPages from '../pages/AllPages.js';

// Catalog snapshot (name + slug) captured from the live store. Slugs are stable
// route identifiers used to pick the exact product card from the listing.
const PRODUCTS: { name: string; slug: string; price: string }[] = [
  { name: 'Rode NT1-A Condenser Mic', slug: 'rode-nt1-a-condenser-mic', price: '$240' },
  { name: 'JBL Charge 4 Bluetooth Speaker', slug: 'jbl-charge-4-bluetooth-speaker', price: '$145' },
  { name: 'Seagate 4TB External Hard Drive', slug: 'seagate-4tb-external-hard-drive', price: '$85' },
  { name: 'SanDisk Ultra Dual Drive 32GB USB 3.0', slug: 'sandisk-ultra-dual-drive-32gb-usb', price: '$15' },
  { name: 'GoPro HERO10 Black', slug: 'gopro-hero10-black', price: '$600' },
  { name: 'Logitech MX Master 3 Wireless Mouse', slug: 'logitech-mx-master-3-wireless-mouse', price: '$90' },
  { name: 'TP-Link Archer AX73 Wi-Fi 6 Router', slug: 'tp-link-archer-ax73-wifi-6-router', price: '$132' },
  { name: 'Apple iPad Air (2022, 5th Gen)', slug: 'apple-ipad-air-2022-5th-gen', price: '$660' },
  { name: 'Samsung 32-inch UHD 4K Smart TV', slug: 'samsung-32-inch-uhd-4k-smart-tv', price: '$432' },
  { name: 'Apple Watch Series 7', slug: 'apple-watch-series-7', price: '$503' },
  { name: 'Dell XPS 13 (2021) Laptop', slug: 'dell-xps-13-2021-laptop', price: '$1,560' },
  { name: 'SanDisk Extreme Pro 3.0 USB-C Memory Card Reader', slug: 'sandisk-extreme-pro-usb-c-card-reader', price: '$36' },
  { name: 'HP LaserJet Pro MFP M428fdw Wireless Printer', slug: 'hp-laserjet-pro-mfp-m428fdw-printer', price: '$306' },
  { name: 'Epson EF-100 Smart Portable Projector', slug: 'epson-ef-100-smart-portable-projector', price: '$900' },
];

// --- shared navigation helpers -------------------------------------------------

async function openListing(allPages: AllPages) {
  await allPages.homePage.clickOnShopNowButton();
  await allPages.allProductsPage.assertAllProductsTitle();
}

// Reach a product detail page by clicking its card in the listing (by slug).
async function openProduct(allPages: AllPages, slug: string) {
  await openListing(allPages);
  await allPages.page.locator(`[href*="/product/${slug}"]`).first().click();
  await expect(allPages.page).toHaveURL(new RegExp(`/product/${slug}`));
}

function addToCart(allPages: AllPages) {
  return allPages.productDetailsPage.clickAddToCartButton(); // asserts "Added to the cart"
}

// --- Flow 1: each product opens to its own detail page (14) ---------------------
test.describe('Catalog · product detail opens', () => {
  for (const p of PRODUCTS) {
    test(`Open product detail: ${p.name}`, async ({ allPages }) => {
      await openProduct(allPages, p.slug);
      await expect(allPages.page.locator('h1').first()).toHaveText(p.name);
    });
  }
});

// --- Flow 2: each product can be added to the cart (14) -------------------------
test.describe('Catalog · add to cart', () => {
  for (const p of PRODUCTS) {
    test(`Add to cart: ${p.name}`, async ({ allPages }) => {
      await openProduct(allPages, p.slug);
      await addToCart(allPages);
    });
  }
});

// --- Flow 3: each added product appears in the cart (14) ------------------------
test.describe('Catalog · product appears in cart', () => {
  for (const p of PRODUCTS) {
    test(`Cart shows: ${p.name}`, async ({ allPages }) => {
      await openProduct(allPages, p.slug);
      await addToCart(allPages);
      await allPages.cartPage.clickOnCartIcon();
      await allPages.cartPage.assertYourCartTitle();
      await expect(allPages.cartPage.getCartItemName().first()).toBeVisible();
    });
  }
});

// --- Flow 4: Reviews tab opens for each product (14) ---------------------------
test.describe('Catalog · reviews tab', () => {
  for (const p of PRODUCTS) {
    test(`Reviews tab opens: ${p.name}`, async ({ allPages }) => {
      await openProduct(allPages, p.slug);
      await allPages.productDetailsPage.clickOnReviewsTab();
      await allPages.productDetailsPage.assertReviewsTab();
    });
  }
});

// --- Flow 5: Additional Information tab opens for each product (14) -------------
test.describe('Catalog · additional info tab', () => {
  for (const p of PRODUCTS) {
    test(`Additional info tab opens: ${p.name}`, async ({ allPages }) => {
      await openProduct(allPages, p.slug);
      await allPages.productDetailsPage.clickOnAdditionalInfoTab();
      await allPages.productDetailsPage.assertAdditionalInfoTab();
    });
  }
});

// --- Flow 6: detail-page quantity can be increased for each product (14) --------
test.describe('Catalog · increase quantity on detail', () => {
  for (const p of PRODUCTS) {
    test(`Increase qty on detail: ${p.name}`, async ({ allPages }) => {
      await openProduct(allPages, p.slug);
      await allPages.productDetailsPage.clickPlusIconToAddQuantity();
      await expect(allPages.productDetailsPage.getTotalQuantity()).toHaveText('2');
    });
  }
});

// --- Flow 7: increase cart quantity for each product (14) ----------------------
test.describe('Catalog · increase quantity in cart', () => {
  for (const p of PRODUCTS) {
    test(`Increase cart qty: ${p.name}`, async ({ allPages }) => {
      await openProduct(allPages, p.slug);
      await addToCart(allPages);
      await allPages.cartPage.clickOnCartIcon();
      await allPages.cartPage.assertYourCartTitle();
      await allPages.cartPage.clickIncreaseQuantityButton();
      await allPages.cartPage.verifyIncreasedQuantity('2');
    });
  }
});

// --- Flow 8: remove each product empties the cart (14) -------------------------
test.describe('Catalog · remove from cart', () => {
  for (const p of PRODUCTS) {
    test(`Remove from cart empties it: ${p.name}`, async ({ allPages }) => {
      await openProduct(allPages, p.slug);
      await addToCart(allPages);
      await allPages.cartPage.clickOnCartIcon();
      await allPages.cartPage.assertYourCartTitle();
      await allPages.cartPage.getRemoveCartItem().first().click({ force: true });
      await allPages.cartPage.verifyEmptyCartMessage();
    });
  }
});

// --- Flow 9: order summary present after adding each product (14) --------------
test.describe('Catalog · cart order summary', () => {
  for (const p of PRODUCTS) {
    test(`Cart order summary present: ${p.name}`, async ({ allPages }) => {
      await openProduct(allPages, p.slug);
      await addToCart(allPages);
      await allPages.cartPage.clickOnCartIcon();
      await allPages.cartPage.assertYourCartTitle();
      await expect(allPages.cartPage.getSubtotalValue()).toBeVisible();
      await expect(allPages.cartPage.getTotalValue()).toBeVisible();
      await expect(allPages.cartPage.getCheckoutButton()).toBeVisible();
    });
  }
});

// --- Flow 10: each product is searchable by its exact name (14) ----------------
test.describe('Catalog · search by name', () => {
  for (const p of PRODUCTS) {
    test(`Search returns product: ${p.name}`, async ({ allPages }) => {
      await openListing(allPages);
      await allPages.inventoryPage.searchProduct(p.name);
      // The matching product card should be present after the search.
      await expect(allPages.page.locator(`[href*="/product/${p.slug}"]`).first()).toBeVisible();
    });
  }
});

// --- Flow 11: each product card shows its name in the listing (14) -------------
test.describe('Catalog · listing card name', () => {
  for (const p of PRODUCTS) {
    test(`Listing card shows name: ${p.name}`, async ({ allPages }) => {
      await openListing(allPages);
      const card = allPages.page.locator(`[href*="/product/${p.slug}"]`).first();
      await expect(card.locator('h2')).toHaveText(p.name);
    });
  }
});

// --- Flow 12: each product card shows its price in the listing (14) ------------
test.describe('Catalog · listing card price', () => {
  for (const p of PRODUCTS) {
    test(`Listing card shows price: ${p.name}`, async ({ allPages }) => {
      await openListing(allPages);
      const card = allPages.page.locator(`[href*="/product/${p.slug}"]`).first();
      await expect(card.locator('p').first()).toContainText(p.price);
    });
  }
});

// --- Flow 13: each product detail page shows its price (14) --------------------
test.describe('Catalog · detail price', () => {
  for (const p of PRODUCTS) {
    test(`Detail page shows price: ${p.name}`, async ({ allPages }) => {
      await openProduct(allPages, p.slug);
      await expect(allPages.page.getByText(p.price, { exact: false }).first()).toBeVisible();
    });
  }
});

// --- Flow 15: brand keyword search returns at least one matching product (12) --
// Each keyword is known to match >= 1 product in the live catalog.
const BRAND_KEYWORDS = [
  'Apple', 'SanDisk', 'GoPro', 'Dell', 'Samsung', 'HP',
  'Epson', 'JBL', 'Logitech', 'Seagate', 'TP-Link', 'Rode',
];
test.describe('Catalog · brand keyword search', () => {
  for (const kw of BRAND_KEYWORDS) {
    test(`Brand search returns results: ${kw}`, async ({ allPages }) => {
      await openListing(allPages);
      await allPages.inventoryPage.searchProduct(kw);
      // At least the first product card should be present for a known brand.
      await expect(allPages.allProductsPage.getNthProduct(1)).toBeVisible();
    });
  }
});

// --- Flow 14: detail-page quantity can be raised to N (5 products x 4 qty = 20) -
const QTY_PRODUCTS = PRODUCTS.slice(0, 5);
const QTY_VALUES = [2, 3, 4, 5];
test.describe('Catalog · quantity stepper values', () => {
  for (const p of QTY_PRODUCTS) {
    for (const qty of QTY_VALUES) {
      test(`Quantity reaches ${qty}: ${p.name}`, async ({ allPages }) => {
        await openProduct(allPages, p.slug);
        // Start at 1; click plus (qty-1) times to reach the target quantity.
        for (let i = 1; i < qty; i++) {
          await allPages.productDetailsPage.clickPlusIconToAddQuantity();
        }
        await expect(allPages.productDetailsPage.getTotalQuantity()).toHaveText(String(qty));
      });
    }
  }
});
